name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pull github repository
        uses: actions/checkout@v2
      - name: hello to me
        run: echo "hello emanuel"